#This is the deployment file written by Vishnu
apiVersion: v1
kind: Service
metadata:
  name: poc-service
spec:
  selector:
    app: pocdemo                             #This is name and deployment file labe name must should be the same.
  type: LoadBalancer
  ports:
    - port: 8088
      targetPort: 8088
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pocdemo
  template:
    metadata:
      labels:
        app: pocdemo
    spec:
      containers:
        - name: poc-vishnu
          image: "981774949705.dkr.ecr.us-east-1.amazonaws.com/pocrepo:latest"
