apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-deepdive-test
  region: ap-south-1
vpc:
  id: "vpc-65d2dd0d"
  subnets:
    public:
      ap-south-1a: { id: subnet-96f2c6fe }
      ap-south-1b: { id: subnet-2607626a }
iam: 
  serviceRoleARN: "arn:aws:iam::010050280358:role/EKS-Cluster-Role"
nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    availabilityZones: ["ap-south-1a", "ap-south-1b"]
    desiredCapacity: 2
    volumeSize: 30
    securityGroups:
      attachIDs: ['sg-c2c50ba2']
    iam:
      instanceProfileARN: "arn:aws:iam::010050280358:instance-profile/EKS-Node-Role"
      instanceRoleARN: "arn:aws:iam::010050280358:role/EKS-Node-Role"
    ssh:
      publicKeyName: DevOps-Champions
      allow: true
